[environment]
host = "http://0.0.0.0:7777"

[[tests]]
http = "example/pastebin/upload.http"
assertions = """
{{ status }} == 200
"""
[tests.outputs]
id = "{{ body | key }}"

[[tests]]
http = "GET {{host}}/raw/{{id}}"
assertions = """
{{ status }} == 200
{{ body }} == "I was created by hat."
"""