name: Continuous Integration

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features --workspace

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly # Using nightly for (a) unstable features of rustfmt and (b) faster clippy redundant_clone lint
          components: rustfmt, clippy
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --all-features --workspace

  examples:
    runs-on: ubuntu-latest
    container:
      image: isaacadams/hat:latest

    env:
      RUST_LOG: off

    services:
      httpmock:
        image: isaacadams/hat-httpmock:latest
        ports:
          - 5000:5000
      pastebin:
        image: mkodockx/docker-pastebin
        ports:
          - 7777:80

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: trycmd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --lib cli_tests

      - name: hat
        run: hat example/local/config.toml
