name: Continuous Integration

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install cargo
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --verbose --all-features --workspace

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install cargo
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --all --check
      - run: cargo clippy --verbose --all-features --workspace

  binaries:
    uses: isaacadams/hat/.github/workflows/rust-binaries.yml@main
    with:
      name: hat
      version: test
      dry-run: true

  examples:
    runs-on: ubuntu-latest

    env:
      RUST_LOG: off

    services:
      httpmock:
        image: isaacadams/hat-httpmock:latest
        ports:
          - 5000:5000
      pastebin:
        image: mkodockx/docker-pastebin
        ports:
          - 7777:80

    steps:
      - uses: actions/checkout@v4

      - name: install cargo
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build
      - run: cargo test --verbose --lib cli_tests
