name: release

permissions: write-all

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  create-binaries:
    uses: isaacadams/hat/.github/workflows/rust-binaries.yml@main
    with:
      name: hat
      version: ${{ github.ref_name }}

  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      # download artifacts from rust-binaries
      - name: download
        run: ls -R # displays the files
        working-directory: bin

      # add release to github
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
