name: try-build

on:
  push:
    branches:
      - 'try-build-*'

jobs:
  try-create-binaries:
    uses: isaacadams/hat/.github/workflows/rust-binaries.yml@main
    with:
      name: hat
      version: ''
